server:
  port: 9191
  servlet:
    context-path: /
spring:
  application:
    name: service-portal

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10  #每间隔10s，向服务端发送一次心跳，证明自己依然存活
    lease-expiration-duration-in-seconds: 50  #50s内没有发送心跳，代表故障，告诉服务端剔除
    prefer-ip-address: true #告诉服务端，服务实例以ip作为链接，而不是取机器名
    instance-id: service-portal #服务实例名称
  client:
    service-url:
      #defaultZone: http://eureka8081:8081/eureka/,http://eureka8082:8082/eureka/,http://eureka8083:8083/eureka/
      defaultZone: http://eureka8081:8081/eureka/
feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: Thread #Thread, Semaphore (隔离策略，线程池or信号量)
          thread:
            timeoutInMilliseconds: 2500 #hystrix默认超时时间，1s
ribbon:
  ReadTimeout: 6000
  ConnectionTimeout: 3000